import { TFormRequest } from "@/shared/types"

export const FormInitialState: TFormRequest = {
    accountNumber: "",
    purposeOfAccount:"",
    bvn: "",
    notificationPreference:"",
    vnin: "",
    channelId: "",
    state: "",
    zipCode: "",
    localGovernment: "",
    customerPhoto: null,
    proofOfIdentityImage: null,
    proofOfAddressImage: null,
    diasporaDocs: null,
    signature: null,
    maritalStatus: "",
    motherMaidenName: "",
    otherReasons:" ",
    FullNameOfKin: "",
    PhoneNumberOfKin: "",
    RelationshipOfKin: "",
    dobOfKin: "",
    HouseNumberOfKin: "",
    StreetNameOfKin: "",
    StateOfKin: "",
    LocalGovernmentOfKin: "",
    PostalZipCodeOfKin: " ",
    RequestType: " ",
    ChannelId: " ",
    linkedIn: "",
    facebook: " ",
    instagram: " ",
    tiktok: " ",
    twitter: " ",
    thread: " ",
    sourceOfWealth: " ",
    employersAddress:" ",

    idNo: " ",
    idType: " ",
    issueDate: "",
    expiryDate: "",

    FirstName: " ",
    LastName: " ",
    MiddleName: " ",
    acceptedTerms: false,
    city: "",

    country: "Nigeria",
    isDiaspora: "no",
    addressLine1: "",
    addressLine2: "",
    dateOfBirth: "",
    citizenshipAddressLine1: "",
    citizenshipAddressLine2: "",
    proofOfNinImage: null,
    title: "",
    status: "",
    employersName: "",
    natureOfBusiness: "",
    numberofYears: "",
    annualIncome: "",
    foreignTaxId: "",
    countryTaxResidence: "",

    streetAddress: "",
    extraDocument: null,
    countryOfTaxResidence: "",
    houseNumber: "",
}
