import { TFormRequest } from "@/shared/types"

export const FormInitialState: TFormRequest = {
    accountNumber: "",
    bvn: "",
    vnin:"",
    channelId:"",
    state: "",
    zipCode: "",
    localGovernment: "",
    customerPhoto: null,
    proofOfIdentityImage: null,
    proofOfAddressImage: null,
    diasporaDocs: null,
    signature: null,
    maritalStatus: "",
    motherMaidenName: "",
    FullNameOfKin: "",
    PhoneNumberOfKin: "",
    RelationshipOfKin: "",
    dobOfKin: "",
    HouseNumberOfKin: "",
    StreetNameOfKin: "",
    StateOfKin: "",
    LocalGovernmentOfKin: "",
    PostalZipCodeOfKin: " ",
    RequestType: " ",
    ChannelId:" ",

    FirstName: " ",
    LastName: " ",
    MiddleName: " ",
    acceptedTerms: false,
    city: "",

    country: "Nigeria",
    isDiaspora: "no",
    addressLine1: "",
    addressLine2: "",
    dateOfBirth: "",
    citizenshipAddressLine1:"",
    citizenshipAddressLine2:"",
    proofOfNinImage: null,
    title: "",
    status: "",
    employersName: "",
    natureOfBusiness: "",
    numberofYears: "",
    annualIncome: "",
    foreignTaxId: "",
    countryTaxResidence: "",
  
    streetAddress: "",
    extraDocument: null,
    countryOfTaxResidence: "",
    houseNumber: ""
}
