import { TFormRequest } from "@/shared/types"

export const FormInitialState: TFormRequest = {
    accountNumber: "",
    bvn: "",
    state: "",
    postalCode: "",
    localGovt: "",
    customerPhoto: null,
    proofOfIdentityImage: null,
    proofOfAddressImage: null,
    diasporaDocs: null,
    signature: null,
    maritalStatus: "",
    motherMaidenName: "",
    FullNameOfKin: "",
    PhoneNumberOfKin: "",
    Documents: [],
    RelationshipOfKin: "",
    DobOfKin: "",
    HouseNumberOfKin: "",
    StreetNameOfKin: "",
    StateOfKin: "",
    LocalGovernmentOfKin: "",
    PostalZipCodeOfKin: " ",
    RequestType: " ",
    FirstName: " ",
    LastName: " ",
    MiddleName: " ",


    acceptedTerms: false,
    city: "",
    country: "Nigeria",
    isDiaspora: "no",
    line1: "",
    line2: "",
    DOB: "",
    proofOfNinImage: null,
    title: "",
    Status: "",
    EmployersName: "",
    NatureOfBusiness: "",
    NumberofYears: "",
    AnnualIncome: "",
    ForeignTaxId: "",
    CountryTaxResidence: "",
    MobileNumber: " ",
    AddressLine1: "",
    AddressLine2: "",
    extraDocument: null,
    countryOfTaxResidence: "",
    Country: ""
}
